services:
  - type: web
    name: lmstudio-dolphin7b
    env: docker
    plan: free
    image: oobabooga/text-generation-webui:latest
    ports:
      - 7860
    envVars:
      - name: CLI_ARGS
        value: "--model TheBloke/dolphin-2.1-mistral-7b --chat --listen --api"
